import { z } from "zod";

export const recommendationSchema = z.object({
  missionId: z.string().min(1, "La mission est obligatoire"),
  sourceId: z.string().min(1, "La source est obligatoire"),
  reportReference: z.string().optional(),
  pageReference: z.string().optional(),
  issuedAt: z.string().min(1, "La date d'émission est obligatoire"),
  entityId: z.string().min(1, "L'entité est obligatoire"),
  directionId: z.string().optional(),
  processId: z.string().optional(),
  riskTypeId: z.string().optional(),
  recommendationTypeId: z.string().optional(),
  rootCauseTypeId: z.string().optional(),
  findingDescription: z.string().min(10, "La description du constat est obligatoire"),
  rootCause: z.string().optional(),
  potentialConsequence: z.string().optional(),
  recommendation: z.string().min(10, "La recommandation est obligatoire"),
  severityId: z.string().optional(),
  probabilityId: z.string().optional(),
  priorityId: z.string().optional(),
  ownerId: z.string().optional(),
  operationalResponsibleId: z.string().optional(),
  initialDueDate: z.string().optional(),
  statusId: z.string().min(1, "Le statut est obligatoire"),
  entityComment: z.string().optional(),
  isRegulator: z.boolean().default(false),
  isRecurrent: z.boolean().default(false),
  financialImpact: z.number().optional(),
  regulatoryImpact: z.number().min(1).max(5).optional(),
  reputationalImpact: z.number().min(1).max(5).optional(),
  operationalImpact: z.number().min(1).max(5).optional(),
  clientImpact: z.number().min(1).max(5).optional(),
  siImpact: z.number().min(1).max(5).optional(),
  legalImpact: z.number().min(1).max(5).optional(),
  complianceImpact: z.number().min(1).max(5).optional(),
  confidentialityLevelId: z.string().optional(),
});

export type RecommendationFormData = z.infer<typeof recommendationSchema>;
